/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HealthApp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author zador
 */
public class FAQGUI extends javax.swing.JFrame {

    /**
     * Creates new form SuportGUI
     */
    public FAQGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qu6Butt = new javax.swing.JButton();
        qu1Butt = new javax.swing.JButton();
        qu2Butt = new javax.swing.JButton();
        qu3Butt = new javax.swing.JButton();
        qu4Butt = new javax.swing.JButton();
        qu5Butt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FAQ");

        qu6Butt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qu6Butt.setForeground(new java.awt.Color(102, 102, 102));
        qu6Butt.setText("How to contact us?");
        qu6Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qu6ButtActionPerformed(evt);
            }
        });

        qu1Butt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qu1Butt.setForeground(new java.awt.Color(102, 102, 102));
        qu1Butt.setText("For what this app?");
        qu1Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qu1ButtActionPerformed(evt);
            }
        });

        qu2Butt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qu2Butt.setForeground(new java.awt.Color(102, 102, 102));
        qu2Butt.setText("Who created this app?");
        qu2Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qu2ButtActionPerformed(evt);
            }
        });

        qu3Butt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qu3Butt.setForeground(new java.awt.Color(102, 102, 102));
        qu3Butt.setText("How mach it cost?");
        qu3Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qu3ButtActionPerformed(evt);
            }
        });

        qu4Butt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qu4Butt.setForeground(new java.awt.Color(102, 102, 102));
        qu4Butt.setText("What is Specialist profile");
        qu4Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qu4ButtActionPerformed(evt);
            }
        });

        qu5Butt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qu5Butt.setForeground(new java.awt.Color(102, 102, 102));
        qu5Butt.setText("Can i seek from a doctor at 3 a.m.?");
        qu5Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qu5ButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qu5Butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(qu4Butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qu3Butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qu2Butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qu1Butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qu6Butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(qu1Butt)
                .addGap(18, 18, 18)
                .addComponent(qu2Butt)
                .addGap(18, 18, 18)
                .addComponent(qu3Butt)
                .addGap(18, 18, 18)
                .addComponent(qu4Butt)
                .addGap(18, 18, 18)
                .addComponent(qu5Butt)
                .addGap(18, 18, 18)
                .addComponent(qu6Butt)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qu1ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qu1ButtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Health app");
    }//GEN-LAST:event_qu1ButtActionPerformed

    private void qu2ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qu2ButtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Made in China");
    }//GEN-LAST:event_qu2ButtActionPerformed

    private void qu3ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qu3ButtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"We endeavored to ensure inclusivity by making the application accessible to a wide audience, and as a result, the app is offered at no cost.");
    }//GEN-LAST:event_qu3ButtActionPerformed

    private void qu4ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qu4ButtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"If you are an expert in some field, you can indicate this.");
    }//GEN-LAST:event_qu4ButtActionPerformed

    private void qu5ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qu5ButtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Of course you can write to us at 3 am, but you can get an answer only after 8am, because normal people sleep at that time. By the way, sleep is very important for your health, so it is recommended to follow a normal regimen. ");
    }//GEN-LAST:event_qu5ButtActionPerformed

    private void qu6ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qu6ButtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"x21516939@student.ncirl.ie");
    }//GEN-LAST:event_qu6ButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAQGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton qu1Butt;
    private javax.swing.JButton qu2Butt;
    private javax.swing.JButton qu3Butt;
    private javax.swing.JButton qu4Butt;
    private javax.swing.JButton qu5Butt;
    private javax.swing.JButton qu6Butt;
    // End of variables declaration//GEN-END:variables
}
